name: Supabase Database Backup

on:
  schedule:
    - cron: "*/2 * * * *"  # Runs every 2 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Create backup directory
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          mkdir -p backups/$TIMESTAMP

      - name: Backup database
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          # Full database backup
          supabase db dump --db-url "$SUPABASE_DB_URL" -f backups/$TIMESTAMP/full_backup.sql
          
          # Create metadata
          echo "{
            \"timestamp\": \"$TIMESTAMP\",
            \"backup_type\": \"full\",
            \"database_url\": \"$SUPABASE_DB_URL\"
          }" > backups/$TIMESTAMP/metadata.json

      - name: Commit and push backup
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add backups/
          git commit -m "Database backup $(date +'%Y-%m-%d %H:%M:%S')"
          git push
